---
- hosts: all
  tasks:
    - name: Default Packages
      sudo: yes
      apt: name={{item}} update_cache=yes
      with_items:
        - openssh-server
        - meld
        - git
        - zsh
        - siege
        - default-jdk
        - apache2-utils
        - filezilla
        - nfs-common
        - nfs-kernel-server
        - dnsmasq
        - mysql-client
        - php5-cli
        - virtualbox
        - terminator
        - vim
        - vagrant

    - name: Add Hipchat to apt sources
      lineinfile: line="deb http://downloads.hipchat.com/linux/apt stable main" dest=/etc/apt/sources.list.d/atlassian-hipchat.list create=yes

    - name: Add Hipchat apt key
      apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key state=present

    - name: Install Hipchat
      apt: name=hipchat update_cache=yes

    - name: Add chrome package list
      lineinfile: line="deb http://dl.google.com/linux/chrome/deb/ stable main" dest=/etc/apt/sources.list.d/google-chrome.list create=yes

    - name: Add Google Chrome key
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

    - name: Install Google Chrome
      apt: name=google-chrome-stable update_cache=yes

